---
title: "NYC Restaurant Inspection Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: sandstone
    orientation: columns
    vertical_layout: fill

---


{data-width=550}
-----------------------------------------------------------------------

### Total Number of Popular Chain Restaurants in NYC

```{r setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

```{r, echo = FALSE}
data(rest_inspec)

boro_rest = rest_inspec %>% 
 select(boro, violation_description, action, score, dba, cuisine_description, inspection_type, critical_flag, grade, street) %>% 
    filter(
    dba %in% c("DUNKIN' DONUTS", "STARBUCKS", "BURGER KING", "SWEETGREEN", "SUBWAY", "MCDONALD'S", "PANERA BREAD", "PARIS BAGUETTE", "PRET A MANGER", "FRESH & CO")
  ) %>% 
  drop_na(score) %>% 
  drop_na(grade)

boro_rest %>%
  select(boro, violation_description, action, score, dba, cuisine_description, inspection_type, critical_flag, grade, street) %>% 
  count(dba) %>% 
  mutate(dba = fct_reorder(dba, n)) %>% 
  plot_ly(x = ~interaction(dba), y = ~n, color = ~dba, type = "bar", colors = "viridis") %>% 
  layout(xaxis = list(title = "Chain Restaurant"), yaxis = list(title = "Count"))
```

{data-width=400}
-----------------------------------------------------------------------

### Scores of Popular Chain Restaurants in NYC

```{r, echo = FALSE, warning = FALSE}
boro_rest %>% 
  mutate(text_label = str_c("Chain: ", dba, "\nGrade: ", grade)) %>% 
  plot_ly(x = ~score, y = ~interaction(boro)) %>% 
  add_boxplot(color = ~dba, text = ~text_label) %>% 
  layout(xaxis = list(title = "Scores"), yaxis = list(title = "Borough"))
```


### Popular Restaurant Chain Restaurants by Level of Critical Violation 

```{r, echo = FALSE, warning = FALSE}
boro_rest %>% 
   select(boro, violation_description, action, score, dba, cuisine_description, inspection_type, critical_flag, grade, street) %>% 
  drop_na(grade) %>% 
  filter(
    dba %in% c("DUNKIN' DONUTS", "STARBUCKS", "BURGER KING", "SWEETGREEN", "SUBWAY", "MCDONALD'S", "PANERA BREAD", "PARIS BAGUETTE", "PRET A MANGER", "FRESH & CO"),
    critical_flag %in% c("Critical", "Not Critical")
  ) %>% 
  drop_na(score) %>% 
  mutate(text_label = str_c("Chain: ", dba, "\nGrade: ", grade, "\nStreet: ", street)) %>% 
  plot_ly(x = ~score, y = ~interaction(critical_flag,boro) ,type = "scatter", mode = "markers",  color = ~dba, text = ~text_label) %>% 
  layout(xaxis = list(title = "Scores"), yaxis = list(title = "Critial Level by Borough"))
```

